<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AnswerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('answer')->insert([
            ['answer' => '1923', 'correct' => 0, 'question_id' => 1],
            ['answer' => '1938', 'correct' => 0, 'question_id' => 1],
            ['answer' => '1917', 'correct' => 0, 'question_id' => 1],
            ['answer' => '1914', 'correct' => 1, 'question_id' => 1],
            ['answer' => 'France', 'correct' => 0, 'question_id' => 2],
            ['answer' => 'Germany', 'correct' => 0, 'question_id' => 2],
            ['answer' => 'Austria', 'correct' => 1, 'question_id' => 2],
            ['answer' => 'Hungary', 'correct' => 0, 'question_id' => 2],
            ['answer' => 'New York', 'correct' => 0, 'question_id' => 3],
            ['answer' => 'Austin', 'correct' => 0, 'question_id' => 3],
            ['answer' => 'Dallas', 'correct' => 1, 'question_id' => 3],
            ['answer' => 'Miami', 'correct' => 0, 'question_id' => 3],
            ['answer' => 'Andrew Jackson', 'correct' => 1, 'question_id' => 4],
            ['answer' => 'Arthur Wellsley', 'correct' => 0, 'question_id' => 4],
            ['answer' => 'Otto von Bismarck', 'correct' => 0, 'question_id' => 4],
            ['answer' => 'Napoleon', 'correct' => 0, 'question_id' => 4],
            ['answer' => 'Bull Halsey', 'correct' => 0, 'question_id' => 5],
            ['answer' => 'George Patton', 'correct' => 0, 'question_id' => 5],
            ['answer' => 'Douglas MacArthur', 'correct' => 1, 'question_id' => 5],
            ['answer' => 'Omar Bradley', 'correct' => 0, 'question_id' => 5],
            ['answer' => 'France', 'correct' => 0, 'question_id' => 6],
            ['answer' => 'Austria', 'correct' => 0, 'question_id' => 6],
            ['answer' => 'Italy', 'correct' => 0, 'question_id' => 6],
            ['answer' => 'England', 'correct' => 1, 'question_id' => 6],
            ['answer' => 'Johannes Gutenberg', 'correct' => 1, 'question_id' => 7],
            ['answer' => 'Benjamin Franklin', 'correct' => 0, 'question_id' => 7],
            ['answer' => 'Sir Isaac Newton', 'correct' => 0, 'question_id' => 7],
            ['answer' => 'Martin Luther', 'correct' => 0, 'question_id' => 7],
            ['answer' => 'The White Death', 'correct' => 0, 'question_id' => 8],
            ['answer' => 'The Black Plague', 'correct' => 0, 'question_id' => 8],
            ['answer' => 'Smallpox', 'correct' => 0, 'question_id' => 8],
            ['answer' => 'The Bubonic Plague', 'correct' => 1, 'question_id' => 8],
            ['answer' => 'Italy and Carthage', 'correct' => 0, 'question_id' => 9],
            ['answer' => 'England and Germany', 'correct' => 0, 'question_id' => 9],
            ['answer' => 'France and England', 'correct' => 1, 'question_id' => 9],
            ['answer' => 'Spain and France', 'correct' => 0, 'question_id' => 9],
            ['answer' => 'Martin Luther', 'correct' => 1, 'question_id' => 10],
            ['answer' => 'Saint Augustus', 'correct' => 0, 'question_id' => 10],
            ['answer' => 'Henry David Thoreau', 'correct' => 0, 'question_id' => 10],
            ['answer' => 'Voltaire', 'correct' => 0, 'question_id' => 10],
            ['answer' => 'Hannibal', 'correct' => 0, 'question_id' => 11],
            ['answer' => 'Julius Caesar', 'correct' => 0, 'question_id' => 11],
            ['answer' => 'William the Conqueror', 'correct' => 0, 'question_id' => 11],
            ['answer' => 'Attila the Hun', 'correct' => 1, 'question_id' => 11],
            ['answer' => 'Henry Repeating Rifle', 'correct' => 0, 'question_id' => 12],
            ['answer' => 'Colt Peacemaker', 'correct' => 0, 'question_id' => 12],
            ['answer' => 'Winchester Model 1873', 'correct' => 1, 'question_id' => 12],
            ['answer' => 'Remington Army Revolver', 'correct' => 0, 'question_id' => 12],
            ['answer' => 'Sylvia Plath', 'correct' => 0, 'question_id' => 13],
            ['answer' => 'Virginia Woolf', 'correct' => 0, 'question_id' => 13],
            ['answer' => 'John Steinbeck', 'correct' => 0, 'question_id' => 13],
            ['answer' => 'William Shakespeare', 'correct' => 1, 'question_id' => 13],
            ['answer' => 'The Three Musketeers', 'correct' => 0, 'question_id' => 14],
            ['answer' => 'The Bible', 'correct' => 1, 'question_id' => 14],
            ['answer' => 'Quotations from Chairman Mao Tse-tung', 'correct' => 0, 'question_id' => 14],
            ['answer' => 'Quran', 'correct' => 0, 'question_id' => 14],
            ['answer' => 'Barley glass', 'correct' => 0, 'question_id' => 15],
            ['answer' => 'Sugar cup', 'correct' => 1, 'question_id' => 15],
            ['answer' => 'Synthetic glass', 'correct' => 0, 'question_id' => 15],
            ['answer' => 'Vinegar glass', 'correct' => 0, 'question_id' => 15],
            ['answer' => 'Windmill', 'correct' => 0, 'question_id' => 16],
            ['answer' => 'Hospital', 'correct' => 0, 'question_id' => 16],
            ['answer' => 'Asylum', 'correct' => 1, 'question_id' => 16],
            ['answer' => 'Hotel', 'correct' => 0, 'question_id' => 16],
            ['answer' => 'Franz Liszt', 'correct' => 0, 'question_id' => 17],
            ['answer' => 'Richard Wagner', 'correct' => 0, 'question_id' => 17],
            ['answer' => 'Frédéric Chopin', 'correct' => 1, 'question_id' => 17],
            ['answer' => 'Antonín Dvorak', 'correct' => 0, 'question_id' => 17],
            ['answer' => 'Marilyn Monroe', 'correct' => 0, 'question_id' => 18],
            ['answer' => 'Lady Gaga', 'correct' => 1, 'question_id' => 18],
            ['answer' => 'Alicia Keys', 'correct' => 0, 'question_id' => 18],
            ['answer' => 'Lana Del Rey', 'correct' => 0, 'question_id' => 18],
            ['answer' => 'Pierre-Auguste Renoir', 'correct' => 1, 'question_id' => 19],
            ['answer' => 'Pablo Picasso', 'correct' => 0, 'question_id' => 19],
            ['answer' => 'Claude Monet', 'correct' => 0, 'question_id' => 19],
            ['answer' => 'Miguel Ângelo', 'correct' => 0, 'question_id' => 19],
            ['answer' => 'Meisje met de parel', 'correct' => 0, 'question_id' => 20],
            ['answer' => 'Whistler\'s Mother', 'correct' => 0, 'question_id' => 20],
            ['answer' => 'The Princesse de Broglie', 'correct' => 0, 'question_id' => 20],
            ['answer' => 'Mona Lisa', 'correct' => 1, 'question_id' => 20],
            ['answer' => '"Philadelphia" and "Forrest Gump"', 'correct' => 1, 'question_id' => 21],
            ['answer' => '"Philadelphia" and "Salving Private Ryan"', 'correct' => 0, 'question_id' => 21],
            ['answer' => '"Salving Private Ryan" and "Cast Away"', 'correct' => 0, 'question_id' => 21],
            ['answer' => '"Cast Away" and "Forrest Gump"', 'correct' => 0, 'question_id' => 21],
            ['answer' => 'Charlize Theron', 'correct' => 0, 'question_id' => 22],
            ['answer' => 'Nicole Kidman', 'correct' => 0, 'question_id' => 22],
            ['answer' => 'Angelina Jolie', 'correct' => 1, 'question_id' => 22],
            ['answer' => 'Cameron Diaz', 'correct' => 0, 'question_id' => 22],
            ['answer' => 'The Beatles', 'correct' => 0, 'question_id' => 23],
            ['answer' => 'Madonna', 'correct' => 0, 'question_id' => 23],
            ['answer' => 'Elvis Presley', 'correct' => 1, 'question_id' => 23],
            ['answer' => 'Ed Sheeran', 'correct' => 0, 'question_id' => 23],
            ['answer' => 'Baby One More Time', 'correct' => 1, 'question_id' => 24],
            ['answer' => 'Toxic', 'correct' => 0, 'question_id' => 24],
            ['answer' => 'Lucky', 'correct' => 0, 'question_id' => 24],
            ['answer' => 'Born to Make You Happy', 'correct' => 0, 'question_id' => 24],
            ['answer' => 'K2', 'correct' => 0, 'question_id' => 25],
            ['answer' => 'Mount Everest', 'correct' => 1, 'question_id' => 25],
            ['answer' => 'Mount Fuji', 'correct' => 0, 'question_id' => 25],
            ['answer' => 'Kilimanjaro', 'correct' => 0, 'question_id' => 25],
            ['answer' => '184', 'correct' => 0, 'question_id' => 26],
            ['answer' => '10363', 'correct' => 0, 'question_id' => 26],
            ['answer' => '5290', 'correct' => 0, 'question_id' => 26],
            ['answer' => '7641', 'correct' => 1, 'question_id' => 26],
            ['answer' => 'South Africa', 'correct' => 1, 'question_id' => 27],
            ['answer' => 'Slovenia', 'correct' => 0, 'question_id' => 27],
            ['answer' => 'Vietnam', 'correct' => 0, 'question_id' => 27],
            ['answer' => 'Cura\u00e7ao', 'correct' => 0, 'question_id' => 27],
            ['answer' => 'Egypt', 'correct' => 0, 'question_id' => 28],
            ['answer' => 'Mexico', 'correct' => 1, 'question_id' => 28],
            ['answer' => 'Guatemala', 'correct' => 0, 'question_id' => 28],
            ['answer' => 'Turkey', 'correct' => 0, 'question_id' => 28],
            ['answer' => 'Hosted the first US Marshall Service', 'correct' => 0, 'question_id' => 29],
            ['answer' => 'In honor of a famous Marshall', 'correct' => 0, 'question_id' => 29],
            ['answer' => 'Due to the outline of the islands in the form of a great star', 'correct' => 0, 'question_id' => 29],
            ['answer' => 'Were named after British explorer John Marshall', 'correct' => 1, 'question_id' => 29],
            ['answer' => 'Tugela falls', 'correct' => 1, 'question_id' => 30],
            ['answer' => 'Browne falls', 'correct' => 0, 'question_id' => 30],
            ['answer' => 'Yosemite falls', 'correct' => 0, 'question_id' => 30],
            ['answer' => 'James Bruce falls', 'correct' => 0, 'question_id' => 30],
            ['answer' => 'Salvador', 'correct' => 0, 'question_id' => 31],
            ['answer' => 'Rio de Janeiro', 'correct' => 1, 'question_id' => 31],
            ['answer' => 'Bras\u00edlia', 'correct' => 0, 'question_id' => 31],
            ['answer' => 'S\u00e3o Paulo', 'correct' => 0, 'question_id' => 31],
            ['answer' => 'Sydney', 'correct' => 0, 'question_id' => 32],
            ['answer' => 'Melbourne', 'correct' => 0, 'question_id' => 32],
            ['answer' => 'Adelaide', 'correct' => 0, 'question_id' => 32],
            ['answer' => 'Camberra', 'correct' => 1, 'question_id' => 32],
            ['answer' => 'Vatican', 'correct' => 1, 'question_id' => 33],
            ['answer' => 'Monaco', 'correct' => 0, 'question_id' => 33],
            ['answer' => 'Nauru', 'correct' => 0, 'question_id' => 33],
            ['answer' => 'Tuvalu', 'correct' => 0, 'question_id' => 33],
            ['answer' => 'Green Lantern', 'correct' => 0, 'question_id' => 34],
            ['answer' => 'Batman', 'correct' => 1, 'question_id' => 34],
            ['answer' => 'Wolverine', 'correct' => 0, 'question_id' => 34],
            ['answer' => 'Spiderman', 'correct' => 0, 'question_id' => 34],
            ['answer' => 'Madagascar', 'correct' => 0, 'question_id' => 35],
            ['answer' => 'Zimbabwe', 'correct' => 1, 'question_id' => 35],
            ['answer' => 'Kenya', 'correct' => 0, 'question_id' => 35],
            ['answer' => 'Rwanda', 'correct' => 0, 'question_id' => 35],
            ['answer' => 'California', 'correct' => 0, 'question_id' => 36],
            ['answer' => 'Texas', 'correct' => 0, 'question_id' => 36],
            ['answer' => 'Alaska', 'correct' => 1, 'question_id' => 36],
            ['answer' => 'Washington', 'correct' => 0, 'question_id' => 36],
            ['answer' => 'Eyelids', 'correct' => 1, 'question_id' => 37],
            ['answer' => 'Feet soles', 'correct' => 0, 'question_id' => 37],
            ['answer' => 'Hands', 'correct' => 0, 'question_id' => 37],
            ['answer' => 'Arms', 'correct' => 0, 'question_id' => 37],
            ['answer' => 'Dichloromethane', 'correct' => 0, 'question_id' => 38],
            ['answer' => 'Acetone', 'correct' => 1, 'question_id' => 38],
            ['answer' => 'Formalin', 'correct' => 0, 'question_id' => 38],
            ['answer' => 'Butanol', 'correct' => 0, 'question_id' => 38],
            ['answer' => 'Throat', 'correct' => 1, 'question_id' => 39],
            ['answer' => 'Intestine', 'correct' => 0, 'question_id' => 39],
            ['answer' => 'Ear', 'correct' => 0, 'question_id' => 39],
            ['answer' => 'Eye', 'correct' => 0, 'question_id' => 39],
            ['answer' => '28', 'correct' => 0, 'question_id' => 40],
            ['answer' => '32', 'correct' => 1, 'question_id' => 40],
            ['answer' => '38', 'correct' => 0, 'question_id' => 40],
            ['answer' => '40', 'correct' => 0, 'question_id' => 40],
            ['answer' => 'Giraffe', 'correct' => 0, 'question_id' => 41],
            ['answer' => 'Elephant', 'correct' => 1, 'question_id' => 41],
            ['answer' => 'Bison', 'correct' => 0, 'question_id' => 41],
            ['answer' => 'Camel', 'correct' => 0, 'question_id' => 41],
            ['answer' => 'Jellyfish', 'correct' => 0, 'question_id' => 42],
            ['answer' => 'Blue whale', 'correct' => 0, 'question_id' => 42],
            ['answer' => 'Octopus', 'correct' => 1, 'question_id' => 42],
            ['answer' => 'Hippopotamus', 'correct' => 0, 'question_id' => 42],
            ['answer' => 'Marie Curie', 'correct' => 1, 'question_id' => 43],
            ['answer' => 'Sigrid Undset', 'correct' => 0, 'question_id' => 43],
            ['answer' => 'Lorne Schindler', 'correct' => 0, 'question_id' => 43],
            ['answer' => 'Irene Hemmingway', 'correct' => 0, 'question_id' => 43],
            ['answer' => 'Foot', 'correct' => 0, 'question_id' => 44],
            ['answer' => 'Hand', 'correct' => 0, 'question_id' => 44],
            ['answer' => 'Chest', 'correct' => 0, 'question_id' => 44],
            ['answer' => 'Ear', 'correct' => 1, 'question_id' => 44],
            ['answer' => 'Luminous spots that we see when rubbing our eyes closed', 'correct' => 1, 'question_id' => 45],
            ['answer' => 'A lung disease', 'correct' => 0, 'question_id' => 45],
            ['answer' => 'An additive to increase the carbonation of a drink', 'correct' => 0, 'question_id' => 45],
            ['answer' => 'Small openings in the solar ring', 'correct' => 0, 'question_id' => 45],
            ['answer' => 'Trema Orientalis', 'correct' => 0, 'question_id' => 46],
            ['answer' => 'Carpobrotus Chilensis', 'correct' => 0, 'question_id' => 46],
            ['answer' => 'Acer Buergerianum', 'correct' => 0, 'question_id' => 46],
            ['answer' => 'Gingko Biloba', 'correct' => 1, 'question_id' => 46],
            ['answer' => 'Oxytocin', 'correct' => 0, 'question_id' => 47],
            ['answer' => 'Insulin', 'correct' => 1, 'question_id' => 47],
            ['answer' => 'Adrenaline', 'correct' => 0, 'question_id' => 47],
            ['answer' => 'Epinephrine', 'correct' => 0, 'question_id' => 47],
            ['answer' => 'Octopus', 'correct' => 0, 'question_id' => 48],
            ['answer' => 'Seahorse', 'correct' => 1, 'question_id' => 48],
            ['answer' => 'Jellyfish', 'correct' => 0, 'question_id' => 48],
            ['answer' => 'Hermit Crab', 'correct' => 0, 'question_id' => 48],
            ['answer' => '1986', 'correct' => 1, 'question_id' => 49],
            ['answer' => '1967', 'correct' => 0, 'question_id' => 49],
            ['answer' => '1978', 'correct' => 0, 'question_id' => 49],
            ['answer' => '1990', 'correct' => 0, 'question_id' => 49],
            ['answer' => '90', 'correct' => 0, 'question_id' => 50],
            ['answer' => '80', 'correct' => 1, 'question_id' => 50],
            ['answer' => '70', 'correct' => 0, 'question_id' => 50],
            ['answer' => '60', 'correct' => 0, 'question_id' => 50],
            ['answer' => 'Greece', 'correct' => 1, 'question_id' => 51],
            ['answer' => 'Italy', 'correct' => 0, 'question_id' => 51],
            ['answer' => 'France', 'correct' => 0, 'question_id' => 51],
            ['answer' => 'China', 'correct' => 0, 'question_id' => 51],
            ['answer' => '3', 'correct' => 0, 'question_id' => 52],
            ['answer' => '1', 'correct' => 0, 'question_id' => 52],
            ['answer' => '5', 'correct' => 1, 'question_id' => 52],
            ['answer' => '6', 'correct' => 0, 'question_id' => 52],
            ['answer' => 'Lance Armstrong', 'correct' => 0, 'question_id' => 53],
            ['answer' => 'Bernard Hinault', 'correct' => 0, 'question_id' => 53],
            ['answer' => 'Fausto Coppi', 'correct' => 0, 'question_id' => 53],
            ['answer' => 'Eddy Merckx', 'correct' => 1, 'question_id' => 53],
            ['answer' => 'Italy', 'correct' => 0, 'question_id' => 54],
            ['answer' => 'Belgium', 'correct' => 0, 'question_id' => 54],
            ['answer' => 'Brazil', 'correct' => 1, 'question_id' => 54],
            ['answer' => 'Germany', 'correct' => 0, 'question_id' => 54],
            ['answer' => 'Santiago Barnab\u00e9u', 'correct' => 0, 'question_id' => 55],
            ['answer' => 'La Cartuja', 'correct' => 0, 'question_id' => 55],
            ['answer' => 'RCDE Stadium', 'correct' => 0, 'question_id' => 55],
            ['answer' => 'Camp Nou', 'correct' => 1, 'question_id' => 55],
            ['answer' => 'Yoga', 'correct' => 0, 'question_id' => 56],
            ['answer' => 'Pilates', 'correct' => 1, 'question_id' => 56],
            ['answer' => 'Crossfit', 'correct' => 0, 'question_id' => 56],
            ['answer' => 'Parkour', 'correct' => 0, 'question_id' => 56],
            ['answer' => '9', 'correct' => 0, 'question_id' => 57],
            ['answer' => '10', 'correct' => 0, 'question_id' => 57],
            ['answer' => '7', 'correct' => 1, 'question_id' => 57],
            ['answer' => '5', 'correct' => 0, 'question_id' => 57],
            ['answer' => 'Judo', 'correct' => 0, 'question_id' => 58],
            ['answer' => 'Sumo Wrestling', 'correct' => 1, 'question_id' => 58],
            ['answer' => 'Karate', 'correct' => 0, 'question_id' => 58],
            ['answer' => 'Akido', 'correct' => 0, 'question_id' => 58],
            ['answer' => 'Ferrrari', 'correct' => 0, 'question_id' => 59],
            ['answer' => 'HRT (Hispania Racing Team)', 'correct' => 0, 'question_id' => 59],
            ['answer' => 'Renault', 'correct' => 1, 'question_id' => 59],
            ['answer' => 'Lotus', 'correct' => 0, 'question_id' => 59],
            ['answer' => 'Mark Selby', 'correct' => 0, 'question_id' => 60],
            ['answer' => 'Ronnie O\'Sullivan', 'correct' => 1, 'question_id' => 60],
            ['answer' => 'Judd Trump', 'correct' => 0, 'question_id' => 60],
            ['answer' => 'Neil Robertson', 'correct' => 0, 'question_id' => 60],
        ]);
    }
}